config/routes.rb
Rails.application.routes.draw do
  resources :tags

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :clients
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user

  validates :last_name, presence: true
  validates :first_name, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clients
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:show, :edit, :update, :destroy]
  def index
    # @clients = Client.all.order("last_name ASC, first_name ASC")
    if user_signed_in?
      @clients = Client.where(user_id: current_user).order("last_name ASC, first_name ASC")
    else
      # redirect_to invalid_form
      redirect_to new_user_session_path
    end
  end

  def show
  end

  def new
    # @client = Client.new
    @client = current_user.clients.build
  end

  def create
    # @client = Client.new(client_params)
    @client = current_user.clients.build(client_params)

    if @client.save
      redirect_to @client
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def find_client
    # @client = Client.find(params[:id])
    @client = current_user.clients.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name, :middle_initial, :name_suffix, :gender, :dob, :phone_number, :email_address, :address_line1, :address_line2, :city, :state, :zip_code, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.haml
= simple_form_for @client, html: {class: "form"} do |f|
  = f.input :first_name, label: "First name:"
  = f.input :last_name, label: "Last name:"
  = f.input :middle_initial, label: "MI:"
  = f.input :name_suffix, label: "Suffix:"
  = f.input :gender, label: "Gender:"
  = f.input :dob, label: "DOB", start_year: Time.now.year - 100, end_year: Time.now.year, order: [:month, :day, :year], required: false
  = f.input :phone_number, label: "Phone:"
  = f.input :email_address, label: "Email:"
  = f.input :address_line1, label: "Address line 1:"
  = f.input :address_line2, label: "Address line 2:"
  = f.input :city, label: "City:"
  = f.input :state, label: "State"
  = f.input :zip_code, label: "Zip:"
  = f.input :description, label: "Description:"
  = f.button :submit

app/views/clients/edit.html.haml
%h1 Edit Client

= render 'form'

= link_to "Cancel", client_path

app/views/clients/new.html.haml
.container
  .col-sm-6
    %h1 Add Client

    = render 'form'

app/views/clients/show.html.haml
%h1 #{@client.last_name}, #{@client.first_name} #{@client.middle_initial}. #{@client.name_suffix}
%p Gender: #{@client.gender}
%p DOB: #{@client.dob}
%p Phone: #{@client.phone_number}
%p Email: #{@client.email_address}
%p Address: #{@client.address_line1}
%p Address: #{@client.address_line2}
%p City: #{@client.city}
%p State: #{@client.state}
%p Zip: #{@client.zip_code}
%p Description: #{@client.description}

= link_to "All Clients", clients_path
= link_to "Edit", edit_client_path(@client)
= link_to "Delete", client_path(@client), method: :delete, data: {confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clientmanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/clients/">Client Manager</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Home", root_path, class: "active" %>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li>User: <strong><%= current_user.email %></strong></li>
                <li>
                  <%= link_to "Account", edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to "Sign In", new_user_session_path %>
                </li>
            <% end %>
            </ul>
          </div>
        </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

</body>
</html>

app/views/tags/_form.html.erb
<%= simple_form_for @tag do |f| %>
    <%= f.input :name, label: "Tag:" %>
    <%= f.input :description, label: "Description:" %>
    <%= f.input :type_of, as: "hidden", value: "client" %>
    <%= f.input :user_id, as: "hidden", value: current_user.id %>
    <%= f.button :submit %>
<% end %>

app/views/welcome/index.html.haml
%h1 Welcome Placeholder